---
title: "Special plot types"
format: html
editor: visual
---

## Heatmaps

Heatmap packages:

[pheatmap](https://cran.r-project.org/web/packages/pheatmap/index.html)

[ComplexHeatmap](https://github.com/jokergoo/ComplexHeatmap)

Expert level specifically for genomic signals:

[https://github.com/jokergoo/EnrichedHeatmap](EnrichedHeatmap)

```{r}
#| warning: false
library(pheatmap)

LGG <- read.delim("data/lgg_tcga_pan_can_atlas_2018_clinical_data.tsv")
```

```{r}
#| warning: false
#| message: false
#| 
ge <- readRDS("data/LGG_GE_small_mat.RDS")

colnames(ge) <- substr(colnames(ge), 1, 15)
LGG_anno <- LGG[colnames(ge),]

pheatmap(ge[1:50,], scale = "row", show_rownames = F, show_colnames = F, colorRampPalette(c("navy", "white", "red"))(50))

pheatmap(ge[1:50,], scale = "row", show_rownames = F, show_colnames = F, colorRampPalette(c("navy", "white", "red"))(50), annotation_col = LGG_anno[,c("Sex", "Cancer.Type.Detailed")])


ann_colors = list(
    Sex = c(Male = "darkblue", Female = "firebrick"),
    Cancer.Type.Detailed = c(Astrocytoma = "#1B9E77", "Low-Grade Glioma (NOS)" = "#D95F02", Oligoastrocytoma = "#7570B3", Oligodendroglioma = "#E7298A")
)
pheatmap(ge[1:50,], scale = "row", show_rownames = F, show_colnames = F, colorRampPalette(c("navy", "white", "red"))(50), annotation_col = LGG_anno[,c("Sex", "Cancer.Type.Detailed")], annotation_colors = ann_colors)


```
